version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: super-secret-password
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: do-not-steal
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local