services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: super-secret-password
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: do-not-steal
    volumes:
      - pgdata:/var/lib/postgresql/data
  todo_server:
    image: spring-todo:latest
    container_name: todo_server
    ports:
    - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
      - logstash
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/todo_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: do-not-steal
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: super-secret-password

  elasticsearch:
    image: bitnami/elasticsearch:8
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTICSEARCH_ENABLE_SECURITY=false
    ports:
      - "9200:9200"

  logstash:
    image: bitnami/logstash:8
    ports:
      - "5000:5000"
    volumes:
      - ./logstash.conf:/bitnami/logstash/pipeline/logstash.conf
    environment:
      - ELASTICSEARCH_ENABLE_SECURITY=false
    depends_on:
      - elasticsearch

  kibana:
    image: bitnami/kibana:8
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  pgdata:
    driver: local